Added terraform plan for pull requests

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -6,9 +6,11 @@ on:
   - cron: '0 1 * * 1' # 1AM (UTC) every monday -- this run will clean up potential old policies
   push:
     branches: [prod, dev]
+  pull_request:
+    branches: [prod, dev]
 
 env:
-  WORKSPACE: ${{ github.ref_name }}
+  WORKSPACE: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
   AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
   TF_VAR_region: eu-north-1
   TF_VAR_organization: carlssonk
@@ -41,6 +43,7 @@ jobs:
     permissions:
       id-token: write
       contents: read
+      pull-requests: write
 
     steps:
       - name: Checkout
@@ -72,8 +75,16 @@ jobs:
             python create_globals.py '${{ toJson(env) }}' workflow_step=$step
             
             chmod +x retry_command.sh
-            if ! ./retry_command.sh "terraform apply -auto-approve"; then
-              echo "Terraform apply failed after all retry attempts"
-              exit 1
+
+            if [[ "${{ github.event_name }}" == "pull_request" ]]; then
+              if ! ./retry_command.sh "terraform plan"; then
+                echo "Terraform plan failed after all retry attempts"
+                exit 1
+              fi
+            else
+              if ! ./retry_command.sh "terraform apply -auto-approve"; then
+                echo "Terraform apply failed after all retry attempts"
+                exit 1
+              fi
             fi
           done
