Refactor

diff --git a/.github/workflows/destroy.yml b/.github/workflows/destroy.yml
--- a/.github/workflows/destroy.yml
+++ b/.github/workflows/destroy.yml
@@ -9,8 +9,12 @@ on:
         description: 'Type "DESTROY" to confirm infrastructure destruction'
         required: true
 
+concurrency: 
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: false
+
 env:
-  WORKSPACE: ${{ github.ref_name }}
+  TARGET_BRANCH: ${{ github.ref_name }}
   AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
   TF_VAR_region: eu-north-1
   TF_VAR_organization: carlssonk
@@ -57,25 +61,42 @@ jobs:
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v2
 
-      - name: Run Terraform for IAM and Resources
-        run: |
-          for step in resources iam; do
-            echo "Running Terraform for $step"
-            
-            terraform init -reconfigure \
-              -backend-config="encrypt=true" \
-              -backend-config="region=${{ env.TF_VAR_region }}" \
-              -backend-config="bucket=${{ env.TF_VAR_organization }}-terraform-state-bucket-${{ env.WORKSPACE }}" \
-              -backend-config="dynamodb_table=${{ env.TF_VAR_organization }}-terraform-lock-table-${{ env.WORKSPACE }}" \
-              -backend-config="key=${step}/terraform.tfstate"
-            
-            terraform workspace select ${{ env.WORKSPACE }} || terraform workspace new ${{ env.WORKSPACE }}
-            
-            python create_globals.py '${{ toJson(env) }}' workflow_step=$step
-            
-            chmod +x retry_command.sh
-            if ! ./retry_command.sh "terraform destroy -auto-approve"; then
-              echo "Terraform apply failed after all retry attempts"
-              exit 1
-            fi
-          done
+      - name: Destroy resources
+        env:
+          TF_VAR_workflow_step: resources
+        run: |          
+          terraform init \
+            -backend-config="encrypt=true" \
+            -backend-config="region=${{ env.TF_VAR_region }}" \
+            -backend-config="bucket=${{ env.TF_VAR_organization }}-terraform-state-bucket-${{ env.TARGET_BRANCH }}" \
+            -backend-config="dynamodb_table=${{ env.TF_VAR_organization }}-terraform-lock-table-${{ env.TARGET_BRANCH }}" \
+            -backend-config="key=resources/terraform.tfstate"
+          
+          python create_globals.py '${{ toJson(env) }}' workflow_step=resources
+          terraform workspace select ${{ env.TARGET_BRANCH }} || terraform workspace new ${{ env.TARGET_BRANCH }}
+          chmod +x retry_command.sh
+          
+          if ! ./retry_command.sh "terraform destroy -auto-approve"; then
+            echo "Terraform failed after all retry attempts"
+            exit 1
+          fi
+
+      - name: Destroy IAM
+        env:
+          TF_VAR_workflow_step: iam
+        run: |          
+          terraform init -reconfigure \
+            -backend-config="encrypt=true" \
+            -backend-config="region=${{ env.TF_VAR_region }}" \
+            -backend-config="bucket=${{ env.TF_VAR_organization }}-terraform-state-bucket-${{ env.TARGET_BRANCH }}" \
+            -backend-config="dynamodb_table=${{ env.TF_VAR_organization }}-terraform-lock-table-${{ env.TARGET_BRANCH }}" \
+            -backend-config="key=iam/terraform.tfstate"
+          
+          python create_globals.py '${{ toJson(env) }}' workflow_step=iam
+          terraform workspace select ${{ env.TARGET_BRANCH }} || terraform workspace new ${{ env.TARGET_BRANCH }}
+          chmod +x retry_command.sh
+          
+          if ! ./retry_command.sh "terraform destroy -lock=false -auto-approve"; then
+            echo "Terraform failed after all retry attempts"
+            exit 1
+          fi
